### ISSUE TITLE
The prune/merge token numbers for the last layer is out of range.

### ISSUE THREAD

**Issue by Bostoncake** [OpenGVLab/DiffRate#4]
![image](https://github.com/OpenGVLab/DiffRate/assets/52281563/f662e390-f781-4175-9449-c0ab1e849199)

I tried to train for compression parameters on ImageNet, and the results are shown above. It is actually OK to use `x[:197]` for `len(x)<197`, since Python will automatically get the whole list. But I think the prune/merge results for the last layer might need to be fixed.

**Comment by ChenMnZ** [comment]
This does not affect the correct results, because we do not execute token compression in the last block.

Actually, in the last layer, we can even compress all the other tokens except class token.
