### ISSUE TITLE
Extreme high pruning FLOPs ratio 

### ISSUE THREAD

**Issue by King4819** [OpenGVLab/DiffRate#6]
Awesome work ! I would like to ask whether the method works well at extreme high pruning FLOPs ratio, for example, pruning 80% FLOPs of deit-small model. If I want to implement such experiment, the only thing I need to adjust is the **--target_flops** argument ?
Hopes to get your reply, thanks !

**Comment by ChenMnZ** [comment]
Yes, you can adjust --target_flops to have a try. 

However, I think that model with extremely pruning ratio would perform worse.

**Comment by King4819** [comment]
@ChenMnZ Thanks for your reply. I would like to ask whether the method is able to get any target FLOPs, e.g., prune 90% FLOPs, can it be achieved by the original train settings in your work ?

**Comment by ChenMnZ** [comment]
@King4819 I am not sure.

If you find that the final FLOPs is always large than the target flops, you can set `lamb` as a larger number.

https://github.com/OpenGVLab/DiffRate/blob/91ae3e376e9c3f9f1e69f580fd902b61de5dfe0e/engine.py#L37C9-L37C14

**Comment by King4819** [comment]
@ChenMnZ Thank you very much for your reply! I will give it a try. Awesome work that solve the handpicked token keep ratio problem in token pruning field!

**Comment by ChenMnZ** [comment]
Thanks for your interesting.
